#81 cogs can now be enabled and disabled using symlinks

diff --git a/scripts/lion b/scripts/lion
--- a/scripts/lion
+++ b/scripts/lion
@@ -2,12 +2,13 @@
 # Control the Lion service.
 # Written by Tiger Sachse.
 
-#COG_DIR="cogs"
+COG_DIR="cogs"
 DOCS_DIR="docs"
 DATA_DIR="data"
 INSTALL_DIR="/opt"
 PACKAGE_NAME="lion"
-#DISABLED_DIR="disabled"
+ENABLED_DIR="enabled"
+DISABLED_DIR="disabled"
 VERSION_FILE="VERSION.txt"
 SERVICE_FILE="lion.service"
 TOKEN_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DATA_DIR/discord.token"
@@ -32,13 +33,13 @@ start_service() {
     systemctl start $SERVICE_FILE
 }
 
-# Kill the service.
-kill_service() {
+# Stop the service.
+stop_service() {
     if [[ $EUID -ne 0 ]]; then
         echo "You must run this function as a root user (or with sudo)."
         exit 1
     fi
-    echo "Killing Lion..."
+    echo "Stopping Lion..."
     systemctl stop $SERVICE_FILE
 }
 
@@ -90,102 +91,109 @@ show_log() {
 
 # Show a simple help message.
 show_help() {
-    printf "Command syntax:\n    $ lion [--flag] <parameter>\n\n"
+    printf "Command syntax:\n    $ lion [--flag] <parameters>\n\n"
     echo "Check out https://github.com/tgsachse/lion for all available flags."
 }
 
-## Enable installed cogs.
-#enable_cogs() {
-#    if [[ $EUID -ne 0 ]]; then
-#        echo "You must run this function as a root user (or with sudo)."
-#        exit 1
-#    fi
-#
-#    ENABLED_COG=false
-#    for COG in "$@"; do
-#        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG"
-#        if [ -d $COG_PATH ]; then
-#            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"
-#            echo "Enabled cog: $COG"
-#            ENABLED_COG=true
-#        else
-#            echo "Cog not found: $COG"
-#        fi
-#    done
-#
-#    if [ "$ENABLED_COG" = true ]; then
-#        printf "\nYou should restart the bot for changes to take effect.\n"
-#    fi
-#}
-#
+# Enable installed cogs.
+enable_cogs() {
+    if [[ $EUID -ne 0 ]]; then
+        echo "You must run this function as a root user (or with sudo)."
+        exit 1
+    fi
+
+    ENABLED_COG=false
+    for COG in "$@"; do
+        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
+        if [ -d $COG_PATH ]; then
+            if [ ! -L "$INSTALL_DIR/$PACKAGE_NAME/$ENABLED_DIR/$COG" ]; then
+                ln -s $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$ENABLED_DIR"
+                rm -f "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG"
+                echo "Enabled cog: $COG"
+                ENABLED_COG=true
+            else
+                echo "Cog already enabled: $COG"
+            fi
+        else
+            echo "Cog not found: $COG"
+        fi
+    done
+
+    if [ "$ENABLED_COG" = true ]; then
+        printf "\nYou should restart the bot for changes to take effect.\n"
+    fi
+}
+
 ## Disable unwanted cogs.
-#disable_cogs() {
-#    if [[ $EUID -ne 0 ]]; then
-#        echo "You must run this function as a root user (or with sudo)."
-#        exit 1
-#    fi
-#
-#    DISABLED_COG=false
-#    for COG in "$@"; do
-#        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
-#        if [ -d $COG_PATH ]; then
-#            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
-#            echo "Disabled cog: $COG"
-#            DISABLED_COG=true
-#        else
-#            echo "Cog not found: $COG"
-#        fi
-#    done
-#
-#    if [ "$DISABLED_COG" = true ]; then
-#        printf "\nYou should restart the bot for changes to take effect.\n"
-#    fi
-#}
-#
-## List all enabled cogs.
-#list_cogs() {
-#    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$COG_DIR)" ]; then
-#        echo "Enabled cogs:"
-#        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"/*; do
-#            COG=$(basename "$COG_PATH")
-#            echo "  $COG"
-#        done
-#    else
-#        echo "No enabled cogs!"
-#    fi
-#}
-#
-## List all disabled cogs.
-#list_disabled_cogs() {
-#    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR)" ]; then
-#        echo "Disabled cogs:"
-#        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"/*; do
-#            COG=$(basename "$COG_PATH")
-#            echo "  $COG"
-#        done
-#    else
-#        echo "No disabled cogs!"
-#    fi
-#}
+disable_cogs() {
+    if [[ $EUID -ne 0 ]]; then
+        echo "You must run this function as a root user (or with sudo)."
+        exit 1
+    fi
+
+    DISABLED_COG=false
+    for COG in "$@"; do
+        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
+        if [ -d $COG_PATH ]; then
+            if [ ! -L "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG" ]; then
+                ln -s $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
+                rm -f "$INSTALL_DIR/$PACKAGE_NAME/$ENABLED_DIR/$COG"
+                echo "Disabled cog: $COG"
+                DISABLED_COG=true
+            else
+                echo "Cog already disabled: $COG"
+            fi
+        else
+            echo "Cog not found: $COG"
+        fi
+    done
+
+    if [ "$DISABLED_COG" = true ]; then
+        printf "\nYou should restart the bot for changes to take effect.\n"
+    fi
+}
+
+# List installed cogs.
+list_cogs() {
+    HEADER="Available cogs:"
+    TARGET_DIR="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"
+    if [ "$1" == "--enabled" ]; then
+        HEADER="Enabled cogs:"
+        TARGET_DIR="$INSTALL_DIR/$PACKAGE_NAME/$ENABLED_DIR"
+    elif [ "$1" == "--disabled" ]; then
+        HEADER="Disabled cogs:"
+        TARGET_DIR="$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
+    fi
+
+    if [ "$(ls -A $TARGET_DIR)" ]; then
+        echo $HEADER
+        for COG_PATH in $TARGET_DIR/*; do
+            COG=$(basename "$COG_PATH")
+            echo "  $COG"
+        done
+    else
+        echo "No cogs found!"
+    fi
+}
 
 # Main entry point to the script.
 case $1 in
     --token)
         add_token $2
         ;;
-    -s|--start)
+    --start)
         start_service
         ;;
-    -k|--kill|--stop)
-        kill_service
+    --stop)
+        stop_service
         ;;
-    -r|--restart)
+    --restart)
         restart_service
         ;;
-    -e|--enable)
+    --enable)
         enable_service
         ;;
-    -d|--disable)
+    --disable)
         disable_service
         ;;
     --status)
@@ -197,19 +205,23 @@ case $1 in
     --log)
         show_log
         ;;
-#    --enable-cogs)
-#        enable_cogs "${@:2}"
-#        ;;
-#    --disable-cogs)
-#        disable_cogs "${@:2}"
-#        ;;
-#    --list-cogs)
-#        list_cogs
-#        ;;
-#    --list-disabled-cogs)
-#        list_disabled_cogs
-#        ;;
-    -h|--help|*)
+    --cogs)
+        case $2 in
+            --enable)
+                enable_cogs "${@:3}"
+                ;;
+            --disable)
+                disable_cogs "${@:3}"
+                ;;
+            --list)
+                list_cogs $3
+                ;;
+            *)
+                show_help
+                ;;
+        esac
+        ;;
+    --help|*)
         show_help
         ;;
 esac
