reorganize repo, also remove cog functions for backend

diff --git a/scripts/lion b/scripts/lion
--- a/scripts/lion
+++ b/scripts/lion
@@ -2,14 +2,15 @@
 # Control the Lion service.
 # Written by Tiger Sachse.
 
-COG_DIR="cogs"
+#COG_DIR="cogs"
 DOCS_DIR="docs"
+DATA_DIR="data"
 INSTALL_DIR="/opt"
 PACKAGE_NAME="lion"
-DISABLED_DIR="disabled"
-TOKEN_FILE="discord.token"
+#DISABLED_DIR="disabled"
 VERSION_FILE="VERSION.txt"
 SERVICE_FILE="lion.service"
+TOKEN_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DATA_DIR/discord.token"
 
 # Add a token for the service.
 add_token() {
@@ -18,7 +19,7 @@ add_token() {
         exit 1
     fi
     echo "Adding token..."
-    echo $1 > "$INSTALL_DIR/$PACKAGE_NAME/$TOKEN_FILE"
+    echo $1 > $TOKEN_PATH
 }
 
 # Start the service.
@@ -93,79 +94,79 @@ show_help() {
     echo "Check out https://github.com/tgsachse/lion for all available flags."
 }
 
-# Enable installed cogs.
-enable_cogs() {
-    if [[ $EUID -ne 0 ]]; then
-        echo "You must run this function as a root user (or with sudo)."
-        exit 1
-    fi
-
-    ENABLED_COG=false
-    for COG in "$@"; do
-        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG"
-        if [ -d $COG_PATH ]; then
-            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"
-            echo "Enabled cog: $COG"
-            ENABLED_COG=true
-        else
-            echo "Cog not found: $COG"
-        fi
-    done
-
-    if [ "$ENABLED_COG" = true ]; then
-        printf "\nYou should restart the bot for changes to take effect.\n"
-    fi
-}
-
-# Disable unwanted cogs.
-disable_cogs() {
-    if [[ $EUID -ne 0 ]]; then
-        echo "You must run this function as a root user (or with sudo)."
-        exit 1
-    fi
-
-    DISABLED_COG=false
-    for COG in "$@"; do
-        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
-        if [ -d $COG_PATH ]; then
-            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
-            echo "Disabled cog: $COG"
-            DISABLED_COG=true
-        else
-            echo "Cog not found: $COG"
-        fi
-    done
-
-    if [ "$DISABLED_COG" = true ]; then
-        printf "\nYou should restart the bot for changes to take effect.\n"
-    fi
-}
-
-# List all enabled cogs.
-list_cogs() {
-    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$COG_DIR)" ]; then
-        echo "Enabled cogs:"
-        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"/*; do
-            COG=$(basename "$COG_PATH")
-            echo "  $COG"
-        done
-    else
-        echo "No enabled cogs!"
-    fi
-}
-
-# List all disabled cogs.
-list_disabled_cogs() {
-    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR)" ]; then
-        echo "Disabled cogs:"
-        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"/*; do
-            COG=$(basename "$COG_PATH")
-            echo "  $COG"
-        done
-    else
-        echo "No disabled cogs!"
-    fi
-}
+## Enable installed cogs.
+#enable_cogs() {
+#    if [[ $EUID -ne 0 ]]; then
+#        echo "You must run this function as a root user (or with sudo)."
+#        exit 1
+#    fi
+#
+#    ENABLED_COG=false
+#    for COG in "$@"; do
+#        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG"
+#        if [ -d $COG_PATH ]; then
+#            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"
+#            echo "Enabled cog: $COG"
+#            ENABLED_COG=true
+#        else
+#            echo "Cog not found: $COG"
+#        fi
+#    done
+#
+#    if [ "$ENABLED_COG" = true ]; then
+#        printf "\nYou should restart the bot for changes to take effect.\n"
+#    fi
+#}
+#
+## Disable unwanted cogs.
+#disable_cogs() {
+#    if [[ $EUID -ne 0 ]]; then
+#        echo "You must run this function as a root user (or with sudo)."
+#        exit 1
+#    fi
+#
+#    DISABLED_COG=false
+#    for COG in "$@"; do
+#        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
+#        if [ -d $COG_PATH ]; then
+#            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
+#            echo "Disabled cog: $COG"
+#            DISABLED_COG=true
+#        else
+#            echo "Cog not found: $COG"
+#        fi
+#    done
+#
+#    if [ "$DISABLED_COG" = true ]; then
+#        printf "\nYou should restart the bot for changes to take effect.\n"
+#    fi
+#}
+#
+## List all enabled cogs.
+#list_cogs() {
+#    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$COG_DIR)" ]; then
+#        echo "Enabled cogs:"
+#        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"/*; do
+#            COG=$(basename "$COG_PATH")
+#            echo "  $COG"
+#        done
+#    else
+#        echo "No enabled cogs!"
+#    fi
+#}
+#
+## List all disabled cogs.
+#list_disabled_cogs() {
+#    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR)" ]; then
+#        echo "Disabled cogs:"
+#        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"/*; do
+#            COG=$(basename "$COG_PATH")
+#            echo "  $COG"
+#        done
+#    else
+#        echo "No disabled cogs!"
+#    fi
+#}
 
 # Main entry point to the script.
 case $1 in
@@ -196,18 +197,18 @@ case $1 in
     --log)
         show_log
         ;;
-    --enable-cogs)
-        enable_cogs "${@:2}"
-        ;;
-    --disable-cogs)
-        disable_cogs "${@:2}"
-        ;;
-    --list-cogs)
-        list_cogs
-        ;;
-    --list-disabled-cogs)
-        list_disabled_cogs
-        ;;
+#    --enable-cogs)
+#        enable_cogs "${@:2}"
+#        ;;
+#    --disable-cogs)
+#        disable_cogs "${@:2}"
+#        ;;
+#    --list-cogs)
+#        list_cogs
+#        ;;
+#    --list-disabled-cogs)
+#        list_disabled_cogs
+#        ;;
     -h|--help|*)
         show_help
         ;;
